name: Generate Changelog

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


jobs:
  cache-changed-files:
    if: github.event.action != 'closed'  # Nur bei Pushes in den PR
    runs-on: ubuntu-latest
    name: Cache Changed Files

    outputs:
      changed-files-cache: ${{ steps.save-cache.outputs.changed-files-cache }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v14.6

      - name: Save Changed Files to Cache
        id: save-cache
        run: |
          echo '${{ steps.changed-files.outputs.all_changed_files }}' > changed-files-cache.json
          echo "changed-files-cache=$(cat changed-files-cache.json)" >> $GITHUB_ENV

      - name: Upload Changed Files as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: changed-files
          path: changed-files-cache.json

  generate-changelog:
    needs: cache-changed-files
    if: github.event.pull_request.merged == true  # Nur wenn der PR gemerged wird
    runs-on: ubuntu-latest

    steps:


      - name: Download Changed Files Artifact
        uses: actions/download-artifact@v3
        with:
          name: changed-files


      - name: Display Changed Files
        run: cat changed-files-cache.json

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Pull Request Data
        id: fetch_pr
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_BODY=$(echo "${{ github.event.pull_request.body }}" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Output Fetched Data
        run: |
          echo "Pull Request Title: $PR_TITLE"
          echo "Pull Request Body: $PR_BODY"
          echo "Pull Request Author: $PR_AUTHOR"


