name: "Changelog Generator"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: "Get OpenAI Input File"
        id: get_diff
        shell: bash
        run: |-

            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_BODY="${{ github.event.pull_request.body }}"
            BASE_REF="${{ github.event.pull_request.base.ref }}"
            HEAD_REF="${{ github.event.pull_request.head.ref }}"

            git fetch origin "$HEAD_REF:$HEAD_REF"
            git fetch origin "$BASE_REF:$BASE_REF"

            git diff "origin/$BASE_REF" > "raw_diff.txt"


            echo "Pull Request Title: $PR_TITLE" > "Input.txt"
            echo "" >> "Input.txt"
            echo "Pull Request Description:" >> "Input.txt"
            echo "$PR_BODY" >> "Input.txt"
            echo "" >> "Input.txt"
            echo "Diff:" >> "Input.txt"
            cat "raw_diff.txt" >> "Input.txt""
            rm raw_diff.txt

            echo "INPUT_FILE=$Input.txt" >> $GITHUB_ENV



      - name: Upload diff file
        uses: actions/upload-artifact@v4
        with:
          name: "INPUT_FILE"
          path: ${{ env.INPUT_FILE }}



