name: "Get Diffs"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
        run: |-
          PULL_NUMBER="$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}"

          git diff "origin/${{ github.event.pull_request.base.ref }}" > "raw_diff.txt"


          echo "Pull Request Title: $PR_TITLE" >> "diff_$PULL_NUMBER"
          echo "" >> "diff_$PULL_NUMBER"
          echo "Pull Request Description:" >> "diff_$PULL_NUMBER"
          echo "$PR_BODY" >> "diff_$PULL_NUMBER"
          echo "" >> "diff_$PULL_NUMBER"
          echo "Diff:" >> "diff_$PULL_NUMBER"
          cat "raw_diff.txt" >> "diff_$PULL_NUMBER"

          echo "diff_$PULL_NUMBER.txt=$(cat diff_$PULL_NUMBER.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Save diff.txt in branche
        run: |

           PULL_NUMBER="$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
           git clean -f
           git config user.name "Update branch"
           git config user.email github-actions@github.com
           git fetch origin
            if git rev-parse --verify origin/changelog; then
              echo "Branch 'changelog' exists. Checking it out."
              git checkout changelog
            else
              echo "Branch 'changelog' does not exist. Creating it."
              git checkout -b changelog
              git push -u origin changelog
            fi

            if [ -f "diff_$PULL_NUMBER.txt" ]; then
              echo "Deleting existing diff file."
              rm "diff_$PULL_NUMBER.txt"
            fi

            git add .
            git commit -m "Update diff_$PULL_NUMBER"
            git push origin changelog

      - name: Upload diff file
        uses: actions/upload-artifact@v4
        with:
          name: diff_$PULL_NUMBER.txt
          path: ./diff_$PULL_NUMBER.txt
