name: "Save Changelog File"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Delete Diff file if it exists"
        run: |-
          PULL_NUMBER=${{ github.event.pull_request.number }}
          FILE_NAME="diff_${PULL_NUMBER}.txt"
          HEAD_REF="${{ github.event.pull_request.head.ref }}"

          if git ls-remote --exit-code origin changelog; then
            echo "Branch 'changelog' exists. Fetching it."
            git fetch origin changelog:changelog
            git checkout changelog

            if [ -f "$FILE_NAME" ]; then
               echo "Deleting existing diff file."
               rm $FILE_NAME
                git add "$FILE_NAME"
                git commit -m "Removed existing diff file: $FILE_NAME"
                git push origin changelog
            else
                echo "File does not exist: $FILE_NAME"
            fi
          else
            echo "Branch 'changelog' does not exist. Skipping file deletion."
          fi

          echo "Switching back to the PR branch: $PR_BRANCH"
          git fetch origin "$HEAD_REF:$HEAD_REF"
          git checkout $HEAD_REF
      - name: "Get diff from pull request"
        id: get_diff
        shell: bash
        run: |-
          PULL_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          HEAD_REF="${{ github.event.pull_request.head.ref }}"


          git fetch origin "$BASE_REF:$BASE_REF"

          git diff "origin/$BASE_REF" > "raw_diff.txt"

          FILE_NAME="diff_${PULL_NUMBER}.txt"
          echo "Pull Request Title: $PR_TITLE" > "$FILE_NAME"
          echo "" >> "$FILE_NAME"
          echo "Pull Request Description:" >> "$FILE_NAME"
          echo "$PR_BODY" >> "$FILE_NAME"
          echo "" >> "$FILE_NAME"
          echo "Diff:" >> "$FILE_NAME"
          cat "raw_diff.txt" >> "$FILE_NAME"
          rm raw_diff.txt

          echo "DIFF_FILE=$FILE_NAME" >> $GITHUB_ENV

      - name: Update diff file in branch
        run: |-
          PULL_NUMBER=${{ github.event.pull_request.number }}
          DIFF_FILE="diff_${PULL_NUMBER}.txt"

          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions@github.com"

          if git ls-remote --exit-code origin changelog; then
            echo "Changelog checkout"
            git checkout changelog
          else
            git checkout -b changelog
          fi

          git add $DIFF_FILE
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update diff file for PR #${PULL_NUMBER}"
            git push origin changelog
          fi

      - name: Upload diff file
        uses: actions/upload-artifact@v4
        with:
          name: diff_file
          path: ${{ env.DIFF_FILE }}
