name: "Get Diffs"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
        run: |-
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}"

          git diff "origin/${{ github.event.pull_request.base.ref }}" > "raw_diff.txt"


          echo "Pull Request Title: $PR_TITLE" > "diff.txt"
          echo "" >> "diff.txt"
          echo "Pull Request Description:" >> "diff.txt"
          echo "$PR_BODY" >> "diff.txt"
          echo "" >> "diff.txt"
          echo "Diff:" >> "diff.txt"
          cat "raw_diff.txt" >> "diff.txt"

          echo "diff=$(cat diff.txt | tr '\n' ' ')" >> $GITHUB_ENV



      - name: Upload diff file
        uses: actions/upload-artifact@v4
        with:
          name: pull-request-diff
          path: ./pull-request-diff
